name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update-wakatime-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install WakaTime CLI
        run: npm install -g @wakatime/wakatime-cli

      - name: Update WakaTime stats in README
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          wakatime --update --section=waka --readme --since=today --timezone="Asia/Kolkata"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update WakaTime stats" || echo "No changes to commit"
          git push
